version: '3.8'

services:
  agent-system:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: ./scripts/run.sh

